name: Base Workflow
description: Reusable base workflow

inputs:
  go-version:
    description: "Go version to use"
    required: true

runs:
  using: "composite"
  steps:
    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version: ${{ inputs.go-version }}

    - name: Tools
      shell: bash
      run: make tools

    - name: Check
      shell: bash
      run: make check

    - name: Run MarkdownLint
      uses: DavidAnson/markdownlint-cli2-action@v18
      with:
        globs: "**/*.md"
